# Generated by Django 2.0.2 on 2018-03-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wind_speed', models.FloatField()),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.FloatField()),
            ],
        ),
    ]
