# Generated by Django 2.0.2 on 2018-03-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ('date',)},
        ),
    ]
