# Generated by Django 2.0.2 on 2018-04-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weatherimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherimage',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
