# Generated by Django 2.1.4 on 2018-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityUploadDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/city/')),
            ],
        ),
    ]
