# Generated by Django 2.1.5 on 2019-03-31 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190316_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.City'),
            preserve_default=False,
        ),
    ]
