# Generated by Django 2.1.5 on 2019-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_weather_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('city_id', 'name', 'country')},
        ),
    ]
