# Generated by Django 2.1.5 on 2019-03-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190331_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
    ]
