# Generated by Django 2.1.5 on 2019-04-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_weather_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city',
        ),
    ]
